site_name: "CS14 SI: Spring 2015"
pages:
    - Home: index.md
    #- [index.md, "Home"]
    #- [lab_week_01.md, "Lab Week 1"]
    - Lecture Week 2: lec_week_02.md
    #- [lec_week_02.md, "Lecture Week 2"]
    - Lab Week 2: lab_week_02.md
    #- [lab_week_02.md, "Lab Week 2"]
    - Lecture Week 3:
        - Big-O Analysis: lec_week_03.md
        - Exceptions: lec_week_03_pt2.md
        - Templates: lec_week_03_pt3.md
    - Lab Week 3: lab_week_03.md
    #- [lec_week_03.md, "Stacks & Queues"]
    #- [lec_week_03_pt2.md, "Exceptions"]
    #- [lab_week_02.md, "Lab Week 2"]
    #- [lab_week_03.md, "Lab Week 3"]
    - Lab Week 4: lab_week_04.md
    #- [lab_week_04.md, "Lab Week 4"]
    - Mock Midterm Week 5: midterm.md
    #- [lab_week_05.md, "Lab Week 5"]
    - Lab Week 5: lab_week_05.md
    #- [lab_week_06.md, "Lab Week 6"]
    #- [lab_week_07.md, "Lab Week 7"]
    #- [lab_week_08.md, "Lab Week 8"]
    #- [lab_week_09.md, "Lab Week 9"]
    # - [notes.md, "Notes"]
theme: readthedocs
